<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Scholarship;
use App\Models\StudentDetail;
use Carbon\Carbon;

class ScholarshipSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Get some student IDs for reference (if they exist)
        $studentIds = StudentDetail::pluck('id')->toArray();
        
        // Sample scholarship data
        $scholarships = [
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Merit Scholarship',
                'code' => 'MERIT-001',
                'amount' => 50000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonths(2),
                'notes' => 'Awarded for outstanding academic performance in Class 10',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Sports Excellence Scholarship',
                'code' => 'SPORTS-001',
                'amount' => 30000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For exceptional performance in district level sports',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Need-Based Scholarship',
                'code' => 'NEED-001',
                'amount' => 75000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(4),
                'notes' => 'Financial assistance for economically disadvantaged students',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Science Olympiad Scholarship',
                'code' => 'SCIENCE-001',
                'amount' => 25000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonth(),
                'notes' => 'For winning first place in state science competition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Arts & Culture Scholarship',
                'code' => 'ARTS-001',
                'amount' => 20000.00,
                'status' => 'rejected',
                'awarded_date' => null,
                'notes' => 'Application did not meet minimum requirements',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Leadership Scholarship',
                'code' => 'LEADER-001',
                'amount' => 40000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For students demonstrating exceptional leadership qualities',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Academic Excellence Scholarship',
                'code' => 'EXCEL-001',
                'amount' => 60000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(3),
                'notes' => 'For maintaining 95%+ average throughout the year',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Community Service Scholarship',
                'code' => 'COMMUNITY-001',
                'amount' => 15000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subWeeks(2),
                'notes' => 'Recognition for outstanding community service contributions',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Innovation Scholarship',
                'code' => 'INNOVATE-001',
                'amount' => 35000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For innovative projects and research work',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'International Competition Scholarship',
                'code' => 'INTERNATIONAL-001',
                'amount' => 100000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subDays(5),
                'notes' => 'For representing school in international competitions',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            // Additional scholarships for better data distribution
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Mathematics Olympiad',
                'code' => 'MATH-002',
                'amount' => 45000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonths(5),
                'notes' => 'For winning national mathematics competition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Debate Championship',
                'code' => 'DEBATE-002',
                'amount' => 18000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(6),
                'notes' => 'For winning inter-school debate competition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Music Excellence',
                'code' => 'MUSIC-002',
                'amount' => 22000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonths(1),
                'notes' => 'For exceptional musical talent and performance',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Computer Programming',
                'code' => 'CODE-002',
                'amount' => 55000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For developing innovative software applications',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Environmental Science',
                'code' => 'ENV-002',
                'amount' => 28000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subWeeks(3),
                'notes' => 'For environmental conservation projects',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Literature Award',
                'code' => 'LIT-002',
                'amount' => 32000.00,
                'status' => 'rejected',
                'awarded_date' => null,
                'notes' => 'Application incomplete - missing required documents',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Robotics Competition',
                'code' => 'ROBOT-002',
                'amount' => 80000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(7),
                'notes' => 'For winning international robotics championship',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Social Service',
                'code' => 'SOCIAL-002',
                'amount' => 12000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subWeeks(1),
                'notes' => 'For outstanding social service contributions',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Photography Award',
                'code' => 'PHOTO-002',
                'amount' => 16000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For exceptional photography skills and portfolio',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Dance Excellence',
                'code' => 'DANCE-002',
                'amount' => 25000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subDays(10),
                'notes' => 'For winning state-level dance competition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Chess Master',
                'code' => 'CHESS-002',
                'amount' => 19000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(8),
                'notes' => 'For achieving chess master title',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Science Research',
                'code' => 'RESEARCH-002',
                'amount' => 90000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonths(9),
                'notes' => 'For groundbreaking scientific research project',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Language Proficiency',
                'code' => 'LANG-002',
                'amount' => 14000.00,
                'status' => 'rejected',
                'awarded_date' => null,
                'notes' => 'Language test score below required threshold',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Art & Design',
                'code' => 'DESIGN-002',
                'amount' => 38000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For exceptional artistic and design work',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Public Speaking',
                'code' => 'SPEAK-002',
                'amount' => 21000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subWeeks(4),
                'notes' => 'For winning public speaking competition',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Technology Innovation',
                'code' => 'TECH-002',
                'amount' => 65000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(10),
                'notes' => 'For developing innovative technology solutions',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Cultural Heritage',
                'code' => 'HERITAGE-002',
                'amount' => 17000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subDays(15),
                'notes' => 'For preserving and promoting cultural heritage',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Health & Wellness',
                'code' => 'HEALTH-002',
                'amount' => 23000.00,
                'status' => 'pending',
                'awarded_date' => null,
                'notes' => 'For promoting health and wellness initiatives',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Entrepreneurship',
                'code' => 'ENTREP-002',
                'amount' => 70000.00,
                'status' => 'approved',
                'awarded_date' => Carbon::now()->subMonths(11),
                'notes' => 'For successful student business ventures',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Film Making',
                'code' => 'FILM-002',
                'amount' => 42000.00,
                'status' => 'rejected',
                'awarded_date' => null,
                'notes' => 'Film content did not meet school guidelines',
                'created_by' => 1,
                'updated_by' => 1,
            ],
            [
                'school_id' => 1,
                'student_id' => !empty($studentIds) ? $studentIds[array_rand($studentIds)] : null,
                'name' => 'Astronomy Research',
                'code' => 'ASTRO-002',
                'amount' => 85000.00,
                'status' => 'paid',
                'awarded_date' => Carbon::now()->subMonths(12),
                'notes' => 'For significant contributions to astronomy research',
                'created_by' => 1,
                'updated_by' => 1,
            ],
        ];

        foreach ($scholarships as $scholarship) {
            Scholarship::create($scholarship);
        }

        $this->command->info('Scholarships seeded successfully!');
    }
}
