@extends('superadmin.app')

@section('title', 'QR Codes - ' . $school->name)

@section('content')
<div class="container-fluid">
    <!-- Page Header -->
    <div class="row">
        <div class="col-12">
            <div class="page-title-box">
                <div class="page-title-right">
                    <ol class="breadcrumb m-0">
                        <li class="breadcrumb-item"><a href="{{ route('superadmin.dashboard') }}">Dashboard</a></li>
                        <li class="breadcrumb-item"><a href="{{ route('superadmin.payment.school-qr-codes.limits') }}">QR Code Limits</a></li>
                        <li class="breadcrumb-item active">{{ $school->name }}</li>
                    </ol>
                </div>
                <h4 class="page-title">QR Codes - {{ $school->name }}</h4>
            </div>
        </div>
    </div>

    <!-- School Info Card -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-body">
                    <div class="row align-items-center">
                        <div class="col-md-2">
                            @if($school->logo)
                                <img src="{{ asset('storage/' . $school->logo) }}" alt="School Logo" class="img-thumbnail" style="max-width: 80px;">
                            @else
                                <div class="avatar-lg">
                                    <div class="avatar-title rounded-circle bg-soft-primary text-primary font-size-24">
                                        <i class="mdi mdi-school"></i>
                                    </div>
                                </div>
                            @endif
                        </div>
                        <div class="col-md-6">
                            <h4 class="mb-1">{{ $school->name }}</h4>
                            <p class="text-muted mb-0">{{ $school->email }} | {{ $school->phone }}</p>
                            <p class="text-muted mb-0">{{ $school->address }}</p>
                        </div>
                        <div class="col-md-4">
                            <div class="row text-center">
                                <div class="col-4">
                                    <h5 class="text-primary">{{ $school->qr_codes_generated }}</h5>
                                    <p class="text-muted mb-0">Generated</p>
                                </div>
                                <div class="col-4">
                                    <h5 class="text-success">{{ $school->getRemainingQrCodes() }}</h5>
                                    <p class="text-muted mb-0">Remaining</p>
                                </div>
                                <div class="col-4">
                                    <h5 class="text-info">{{ $school->qr_code_limit }}</h5>
                                    <p class="text-muted mb-0">Limit</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

    <!-- QR Codes List -->
    <div class="row">
        <div class="col-12">
            <div class="card">
                <div class="card-header">
                    <div class="row align-items-center">
                        <div class="col">
                            <h4 class="header-title">Generated QR Codes</h4>
                            <p class="text-muted mb-0">All QR codes generated by this school</p>
                        </div>
                        <div class="col-auto">
                            <a href="{{ route('superadmin.payment.school-qr-codes.limits') }}" class="btn btn-outline-secondary">
                                <i class="mdi mdi-arrow-left"></i> Back to Limits
                            </a>
                        </div>
                    </div>
                </div>
                <div class="card-body">
                    @if($qrCodes->count() > 0)
                        <div class="table-responsive">
                            <table class="table table-striped table-bordered">
                                <thead>
                                    <tr>
                                        <th>#</th>
                                        <th>Title</th>
                                        <th>Description</th>
                                        <th>Amount</th>
                                        <th>Status</th>
                                        <th>Generated Date</th>
                                        <th>Actions</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    @foreach($qrCodes as $index => $qrCode)
                                        <tr>
                                            <td>{{ $index + 1 }}</td>
                                            <td>
                                                <strong>{{ $qrCode->title }}</strong>
                                            </td>
                                            <td>{{ Str::limit($qrCode->description, 50) }}</td>
                                            <td>₹ {{ number_format($qrCode->amount, 2) }}</td>
                                            <td>
                                                @if($qrCode->status)
                                                    <span class="badge bg-success">Active</span>
                                                @else
                                                    <span class="badge bg-secondary">Inactive</span>
                                                @endif
                                            </td>
                                            <td>{{ $qrCode->created_at->format('d M Y H:i A') }}</td>
                                            <td>
                                                <div class="btn-group" role="group">
                                                    <a href="{{ route('superadmin.payment.school-qr-codes.show', $qrCode) }}" 
                                                       class="btn btn-sm btn-outline-primary" title="View">
                                                        <i class="mdi mdi-eye"></i>
                                                    </a>
                                                    <a href="{{ route('superadmin.payment.school-qr-codes.edit', $qrCode) }}" 
                                                       class="btn btn-sm btn-outline-secondary" title="Edit">
                                                        <i class="mdi mdi-pencil"></i>
                                                    </a>
                                                    <a href="{{ route('superadmin.payment.school-qr-codes.download-qr', $qrCode) }}" 
                                                       class="btn btn-sm btn-outline-success" title="Download">
                                                        <i class="mdi mdi-download"></i>
                                                    </a>
                                                </div>
                                            </td>
                                        </tr>
                                    @endforeach
                                </tbody>
                            </table>
                        </div>
                    @else
                        <div class="text-center py-5">
                            <div class="avatar-lg mx-auto mb-4">
                                <div class="avatar-title rounded-circle bg-soft-primary text-primary font-size-24">
                                    <i class="mdi mdi-qrcode"></i>
                                </div>
                            </div>
                            <h5 class="text-muted">No QR Codes Generated</h5>
                            <p class="text-muted">This school hasn't generated any QR codes yet.</p>
                        </div>
                    @endif
                </div>
            </div>
        </div>
    </div>

    <!-- Payment Status Alert -->
    @if($school->needsPaymentForQrCodes())
        <div class="row">
            <div class="col-12">
                <div class="alert alert-warning alert-dismissible fade show" role="alert">
                    <i class="mdi mdi-alert-circle me-2"></i>
                    <strong>Payment Required!</strong> This school has generated 3 or more QR codes and needs to make a payment to continue generating more QR codes.
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
                </div>
            </div>
        </div>
    @endif
</div>
@endsection

@push('scripts')
<script>
$(document).ready(function() {
    // Initialize tooltips
    $('[data-bs-toggle="tooltip"]').tooltip();
});
</script>
@endpush
